#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

enum layers{
    BASE=0,
    SYMB,
    NAVI,
    NUMB,
    FUNC,
};

enum keycode_aliases{
    //Left Home Row Modes
    HM_N=LCTL_T(KC_N),
    HM_R=LALT_T(KC_R),
    HM_T=LGUI_T(KC_T),
    HM_S=LSFT_T(KC_S),
    //Right Home Row Modes
    HM_H=RSFT_T(KC_H),
    HM_A=RGUI_T(KC_A),
    HM_E=RALT_T(KC_E),
    HM_I=RCTL_T(KC_I),
}  
/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [BASE] = LAYOUT_split_3x5_2(
        KC_B,  KC_L,  KC_D,  KC_C,  KC_V,                                               KC_J,  KC_Y,  KC_O   ,  KC_U   ,  KC_COMM, 
        HM_N,  HM_R,  HM_T,  HM_S,  KC_G,                                               KC_P,  HM_H,  HM_A   ,  HM_E   ,  HM_I,
        KC_X,  KC_Q,  KC_M,  KC_W,  KC_Z,                                               KC_K,  KC_F,  KC_QUOT,  KC_SCLN,  KC_DOT, 
                                  KC_SPC,  KC_TAB,                           KC_ENT,  KC_BSPC
      ),
    [SYMB] = LAYOUT_split_3x5_2(
        KC_B,  KC_L,  KC_D,  KC_C,  KC_V,                                               KC_J,  KC_Y,  KC_O   ,  KC_U   ,  KC_COMM, 
        HM_N,  HM_R,  HM_T,  HM_S,  KC_G,                                               KC_P,  HM_H,  HM_A   ,  HM_E   ,  HM_I,
        KC_X,  KC_Q,  KC_M,  KC_W,  KC_Z,                                               KC_K,  KC_F,  KC_QUOT,  KC_SCLN,  KC_DOT,
                                  KC_SPC,  KC_TAB,                           KC_ENT,  KC_BSPC

      ),
    [NAVI] = LAYOUT_split_3x5_2(
        KC_B,  KC_L,  KC_D,  KC_C,  KC_V,                                               KC_J,  KC_Y,  KC_O   ,  KC_U   ,  KC_COMM, 
        HM_N,  HM_R,  HM_T,  HM_S,  KC_G,                                               KC_P,  HM_H,  HM_A   ,  HM_E   ,  HM_I,
        KC_X,  KC_Q,  KC_M,  KC_W,  KC_Z,                                               KC_K,  KC_F,  KC_QUOT,  KC_SCLN,  KC_DOT,
                                  KC_SPC,  KC_TAB,                           KC_ENT,  KC_BSPC

      ),
    [NUMB] = LAYOUT_split_3x5_2(
        KC_B,  KC_L,  KC_D,  KC_C,  KC_V,                                               KC_J,  KC_Y,  KC_O   ,  KC_U   ,  KC_COMM, 
        HM_N,  HM_R,  HM_T,  HM_S,  KC_G,                                               KC_P,  HM_H,  HM_A   ,  HM_E   ,  HM_I,
        KC_X,  KC_Q,  KC_M,  KC_W,  KC_Z,                                               KC_K,  KC_F,  KC_QUOT,  KC_SCLN,  KC_DOT,
                                  KC_SPC,  KC_TAB,                           KC_ENT,  KC_BSPC

      ),
    [FUNC] = LAYOUT_split_3x5_2(
        KC_B,  KC_L,  KC_D,  KC_C,  KC_V,                                               KC_J,  KC_Y,  KC_O   ,  KC_U   ,  KC_COMM, 
        HM_N,  HM_R,  HM_T,  HM_S,  KC_G,                                               KC_P,  HM_H,  HM_A   ,  HM_E   ,  HM_I,
        KC_X,  KC_Q,  KC_M,  KC_W,  KC_Z,                                               KC_K,  KC_F,  KC_QUOT,  KC_SCLN,  KC_DOT,
                                  KC_SPC,  KC_TAB,                           KC_ENT,  KC_BSPC

      )
};

