name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: master
    # Bypasses the dubious ownership error by declaring the safe directory environment rules
    env:
      GIT_CONFIG_GLOBAL_COUNT: 1
      GIT_CONFIG_GLOBAL_KEY_0: safe.directory
      GIT_CONFIG_GLOBAL_VALUE_0: /__w/qmk_userspace/qmk_userspace

  publish:
    name: 'QMK Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@main
    if: always() && !cancelled()
    needs: build
